
bufete_tipocaso:
    resource: "@BufeteBundle/Resources/config/routing/tipocaso.yml"
    prefix:   /tipocaso

bufete_paises:
    resource: "@BufeteBundle/Resources/config/routing/paises.yml"
    prefix:   /paises

login:
    path: /login
    defaults: {_controller: BufeteBundle:Auth:login}

login_check:
    path: /login_check

logout:
    path: /logout

bufete_homepage:
    path:     /home
    defaults: { _controller: BufeteBundle:Default:index }

bufete_personas:
        resource: "@BufeteBundle/Resources/config/routing/personas.yml"
        prefix:   /personas

bufete_demandantes:
        resource: "@BufeteBundle/Resources/config/routing/demandantes.yml"
        prefix:   /demandantes

bufete_laborales:
        resource: "@BufeteBundle/Resources/config/routing/laborales.yml"
        prefix:   /laborales

bufete_civiles:
        resource: "@BufeteBundle/Resources/config/routing/civiles.yml"
        prefix:   /civiles

bufete_tipoparcticante:
        resource: "@BufeteBundle/Resources/config/routing/tipoparcticante.yml"
        prefix:   /tipoparcticante

bufete_clinicas:
        resource: "@BufeteBundle/Resources/config/routing/clinicas.yml"
        prefix:   /clinicas

bufete_casos:
        resource: "@BufeteBundle/Resources/config/routing/casos.yml"
        prefix:   /casos

bufete_departamentos:
        resource: "@BufeteBundle/Resources/config/routing/departamentos.yml"
        prefix:   /departamentos

bufete_ciudad:
        resource: "@BufeteBundle/Resources/config/routing/ciudad.yml"
        prefix:   /ciudad

bufete_estadosciviles:
        resource: "@BufeteBundle/Resources/config/routing/estadosciviles.yml"
        prefix:   /estadosciviles

bufete_bufetes:
        resource: "@BufeteBundle/Resources/config/routing/bufetes.yml"
        prefix:   /bufetes

bufete_trabajos:
        resource: "@BufeteBundle/Resources/config/routing/trabajos.yml"
        prefix:   /trabajos

bufete_tipoasunto:
        resource: "@BufeteBundle/Resources/config/routing/tipoasunto.yml"
        prefix:   /tipoasunto

bufete_tribunales:
        resource: "@BufeteBundle/Resources/config/routing/tribunales.yml"
        prefix:   /tribunales

bufete_estudiantes:
        resource: "@BufeteBundle/Resources/config/routing/estudiantes.yml"
        prefix:   /estudiantes

bufete_infofinal:
        resource: "@BufeteBundle/Resources/config/routing/infofinal.yml"
        prefix:   /infofinal

bufete_revisiones:
        resource: "@BufeteBundle/Resources/config/routing/revisiones.yml"
        prefix:   /revisiones

bufete_asignacionclinica:
        resource: "@BufeteBundle/Resources/config/routing/asignacionclinica.yml"
        prefix:   /asignacionclinica
