casos_casoslaborales:
    path:     /casoslaborales
    defaults: { _controller: "BufeteBundle:Casos:laboralesEstudiante" }
    methods:  GET

casos_casosciviles:
    path:     /casosciviles
    defaults: { _controller: "BufeteBundle:Casos:civilesEstudiante" }
    methods:  GET

casos_indexlaborales:
    path:     /laborales
    defaults: { _controller: "BufeteBundle:Casos:indexLaborales" }
    methods:  GET

casos_indexciviles:
    path:     /civiles
    defaults: { _controller: "BufeteBundle:Casos:indexCiviles" }
    methods:  GET

casos_showlaboral:
    path:     /showlaboral
    defaults: { _controller: "BufeteBundle:Casos:mostrarLaboral" }
    methods:  [GET, POST]

casos_verlaboral:
    path:     /{idCaso}/laboral
    defaults: { _controller: "BufeteBundle:Casos:showLaboral" }
    methods:  GET

casos_showcivil:
    path:     /showcivil
    defaults: { _controller: "BufeteBundle:Casos:mostrarCivil" }
    methods:  [GET, POST]

casos_vercivil:
    path:     /{idCaso}/civil
    defaults: { _controller: "BufeteBundle:Casos:showCivil" }
    methods:  GET

casos_printcivil:
    path:     /{idCaso}/printcivil
    defaults: { _controller: "BufeteBundle:Casos:printCivil" }
    methods:  GET

casos_printlaboral:
    path:     /{idCaso}/printlaboral
    defaults: { _controller: "BufeteBundle:Casos:printlaboral" }
    methods:  GET

casos_newlaboral:
    path:     /newlaboral
    defaults: { _controller: "BufeteBundle:Casos:newLaboral" }
    methods:  [GET, POST]

casos_newcivil:
    path:     /newcivil
    defaults: { _controller: "BufeteBundle:Casos:newCivil" }
    methods:  [GET, POST]

casos_editlaboral:
    path:     /{idCaso}/editlaboral
    defaults: { _controller: "BufeteBundle:Casos:editLaboral" }
    methods:  [GET, POST]

casos_editcivil:
    path:     /{idCaso}/editcivil
    defaults: { _controller: "BufeteBundle:Casos:editCivil" }
    methods:  [GET, POST]

casos_delete:
    path:     /{idCaso}/delete
    defaults: { _controller: "BufeteBundle:Casos:delete" }
    methods:  DELETE

casos_printcivil:
    path:     /{idCaso}/printcivil
    defaults: { _controller: "BufeteBundle:Casos:printCivil" }
    methods:  GET
